### ISSUE TITLE
How many clusters were used in the final modeling?

### ISSUE THREAD

**Issue by benmwebb** [integrativemodeling/mediator#1]
Looking at the scripts in `analysis/clustering/`, some assume a single cluster, some 4 clusters, some 8 clusters, and some 10. And you have output models for both a single cluster and 4 clusters (although precision, density localization, and RMSF info only for the 4-cluster case). Which corresponds to the models in the actual publication?

**Comment by benmwebb** [comment]
The paper suggests 4. So what is the purpose of the `analysis/clustering/kmeans_weight_500_1` directory?

**Comment by mtrnka** [comment]
In the paper, Figure 2-supplement 4 has some analysis done on "All Clusters"... this is the 1-cluster case and the directory you ask about.  Everything else in the paper is on the 4-cluster analysis.  

I'm not sure as to why some of the precision scripts have 10 clusters specified.  It seems to be a holdover from a previous analysis that wasn't used in the paper.  I don't seem to have access to our original data repository that had the analysis scripts on it.

**Comment by benmwebb** [comment]
Ah, I missed that figure. Thanks! All clear now.
