### ISSUE TITLE
Sequence for med5

### ISSUE THREAD

**Issue by benmwebb** [integrativemodeling/mediator#2]
I'm a bit puzzled about the model for the `med5` subunit. The FASTA file contains 1132 residues, but the [Python script](https://github.com/integrativemodeling/mediator/blob/master/sampling/modeling/modeling.py) says

```
 ("med5", "med5_1", 0.40, fastadirectory+"med5.fasta", "med5", "BEADS", None, (1,1146,0), True, 40, 15, [19,12,15], 0, None, None, [15]),
```

i.e. a residue range of 1-1146. So as far as I can tell it adds extra beads to the end of the model (the S chain) to account for an extra phantom 14 residues. Am I reading that right?

**Comment by mtrnka** [comment]
Ahh... this seems to just be a typo/bug.  With the beads size being 40 though, I don't think it actually added any extra beads, there should be 29 either way.

**Comment by benmwebb** [comment]
Ah yes, you're right, the C terminal bead just ends up being a little bigger than it should be - probably doesn't affect the modeling much.
