### ISSUE TITLE
Where are the output trajectories?

### ISSUE THREAD

**Issue by benmwebb** [integrativemodeling/mediator#4]
Normally I would expect to see one or more directories with output models (prior to clustering), for example in an `output` subdirectory ([here](https://github.com/integrativemodeling/exosome/tree/master/modeling-scripts_Rrp6.1/output) is the equivalent for the exosome modeling) but I don't see that for Mediator.

I'm sure that these trajectories are too big to fit in a GitHub repository, which is why they weren't uploaded in the first place. But I'd still like to have them for reference. We can upload them to Zenodo or (worst case) put them on the Sali lab's FTP site. Where are they?

**Comment by benmwebb** [comment]
@Pellarin @cgreenberg Any idea where these trajectories can be found?

**Comment by benmwebb** [comment]
Per Riccardo, most likely they are (somewhere) in `/salilab/park1/pellarin/mediator.tar.xz`

**Comment by Pellarin** [comment]
Yes, if we can untar that 30GB file somewhere, I can definitely look into it!

**Comment by benmwebb** [comment]
See `/salilab/park1/pellarin/no-backup/mediator/`.

**Comment by Pellarin** [comment]
in `/salilab/park1/pellarin/no-backup/mediator/for_publication/analysis`
the directories `clustering  clustering_half1  clustering_half2  clustering_jackknifing` contains the clustering analysis published in the paper. In each directory look the `clustering.py` file which contains the path of the original trajectories. For instance, for `clustering/clustering.py` you have:

```
"../../run20/modeling.split_density.scale_radii.two_bayesian_classes-1.1",
"../../run20/modeling.split_density.scale_radii.two_bayesian_classes-1.2",
"../../run20/modeling.split_density.scale_radii.two_bayesian_classes-1.3",
"../../run20/modeling.split_density.scale_radii.two_bayesian_classes-1.4",
"../../run28/modeling.split_density.scale_radii.two_bayesian_classes-1.5",
"../../run28/modeling.split_density.scale_radii.two_bayesian_classes-1.6",
"../../run28/modeling.split_density.scale_radii.two_bayesian_classes-1.7",
"../../run28/modeling.split_density.scale_radii.two_bayesian_classes-1.8",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.9",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.10",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.11",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.12",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.13",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.14",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.15",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.16",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.17",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.18",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.19",
"../../run31/modeling.split_density.scale_radii.two_bayesian_classes-1.20"
```

**Comment by benmwebb** [comment]
Perfect, thanks Riccardo! I'll archive these directories at Zenodo - they're not too big.

**Comment by Pellarin** [comment]
Awesome! Thanks!
