### ISSUE TITLE
IMP 2.13.0 incompatible?

### ISSUE THREAD

**Issue by heejongkim** [integrativemodeling/mediator#6]
Hi,

I'd like to reproduce the result with this repository under manually compiled IMP 2.13.0.
As I got the entire zip file from IMP homepage and tried to execute "modeling.py".
I got error with IMP.pmi1.xxx can't found.
most of them were ok with just changing IMP.pmi1 to IMP.pmi, which is version 2.
However, representation one seems a little bit tricky for me as a new comer who doesn't have much of background with pmi1 and the transition requires the understand of both version 1 and 2.

Would it be possible if you can guide me how to make changes to move from pmi1 to pmi2?
Or is there any other ways to detour the issue?

Thank you so much.

best,
heejong

**Comment by benmwebb** [comment]
IMP.pmi1 is maintained as a submodule. Most likely you forgot to run `git submodule update --init ` after cloning the IMP repository but before compilation (see the [IMP install docs](https://integrativemodeling.org/2.13.0/doc/manual/installation.html)).

**Comment by heejongkim** [comment]
OMG.
I completely overlooked it.
After having fresh git clone with your suggestion, modeling.py started working without any import error msg.

Thank you so much. I really appreciate it.

best,
heejong
